name: Run trend.py

on:
  workflow_dispatch:  # Позволява ръчно пускане от GitHub UI
  schedule:
    - cron: '0 * * * *'  # Всеки час (на 0-та минута)

jobs:
  run-trend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trend.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python trend.py
